namespace DFEJobs.Migrations
{
    using System;
    using System.Data.Entity.Migrations;

    public partial class AddMoreJobs : DbMigration
    {
        public override void Up()
        {
            Sql(@"
                INSERT INTO Jobs (Title, Location, Department, Salary, Description) VALUES ('Head of New Business Aerospace', 'London', 'Defence', 90000, 'We are looking to strengthen our team with the recruitment of a Head of New Business Aerospace & Defence UK. The purpose of the role will be to obtain new business and grow existing clients to achieve specified sales targets to match the strategic ambition of the business specifically within the Aerospace industries.' + char(13) + '' + char(13) + 'Responsibilities' + char(13) + '' + char(13) + '- Acquire new Aerospace industries related customers through individual prospecting' + char(13) + '- Pursue New Business covering multi modal transportation with a key focus on Air, Road and Sea within the Aerospace and Defence vertical' + char(13) + '- Achieve existing customer growth alongside new business targets' + char(13) + '- Manage the team in the Aerospace vertical to ensure all opportunities are maximised' + char(13) + '- Responsible for achieving set sales targets' + char(13) + '- Increase market share through strategic formulas' + char(13) + '' + char(13) + 'Experience/Skills' + char(13) + '' + char(13) + '- International Logistics experience across Air, Road, Sea & Courier with a focus on Aerospace & Defence' + char(13) + '- Proven sales track record' + char(13) + '- Ability to create and implement sales strategies' + char(13) + '- Strong working knowledge of the Aerospace and Defence sector' + char(13) + '- Target driven');
                INSERT INTO Jobs (Title, Location, Department, Salary, Description) VALUES ('C# VR/Simulation Software Engineer', 'Camerbley', 'Software', 50000, 'As a C# software engineer you will join a project team developing high quality bespoke software and applications to meet customer needs. Working in a fast-paced environment, you will enjoy the variety and challenges that working on multiple projects brings.' + char(13) + '' + char(13) + 'Day to day activities include, but are not limited to:' + char(13) + '' + char(13) + '•The design and development of efficient and effective code' + char(13) + '•Design and implement tests, using automated integration and testing tools' + char(13) + '•Participate in project reviews' + char(13) + '•Working with your colleagues on problem resolution' + char(13) + '' + char(13) + 'Skills Required' + char(13) + '' + char(13) + '•Programming skills in C#' + char(13) + '•Problem solving nature' + char(13) + '•Strong organisational and communications skills' + char(13) + '');
                INSERT INTO Jobs (Title, Location, Department, Salary, Description) VALUES ('Principal Systems Engineer', 'Ruislip', 'Defence', 30000, 'As a Principal Systems Engineer you will be part of a growing world class team, working on technically challenging products that need to be designed to withstand harsh environments. Your responsibilities will incorporate working across the full design lifecycle on multiple projects simultaneously, mentoring junior engineers, and taking the lead or being the design authority on company projects, and therefore being able to hit the ground running is crucial to this role.');
                INSERT INTO Jobs (Title, Location, Department, Salary, Description) VALUES ('Avionics Design Engineer', 'Melbourn, Royston', 'Defence', 52000, 'The Electronics Engineer will be a key member of a high calibre team of Electronics and Firmware Engineers. Working in a purpose built and state-of-the-art facility, you will apply your hardware electronics design skills to a range of fascinating projects covering areas such as commercial avionics, air traffic control systems, electronic warfare, radar and sonar - and occasionally more diverse projects such as advanced data protection. Project variety is guaranteed - no two projects and no two days will ever be the same. On top of this, the company offer a superb salary & benefits package with excellent opportunities for career progression. Employees and innovation are at the heart of this business so you can expect a strong personal development programme whilst working on unique and market disruptive products.' + char(13) + '' + char(13) + 'The Electronics Design Engineer will be involved in all stages of technology and product development including design specification, analysis, computational modelling, prototype design, laboratory testing, process development and manufacturing.' + char(13) + '');
                INSERT INTO Jobs (Title, Location, Department, Salary, Description) VALUES ('Senior Software Developer', 'Reading, Berkshire', 'Software', 72000, 'Senior Software Developer required by an excellent client whose development team is based in Reading, Berkshire. The successful Senior Software Developer will be developing new features to enhance our clients SaaS product using some of the latest technologies. As well as writing excellent code, you will be expected to offer support to more junior developers within the team communication with internal teams and managers. Our clients modern and collaborative working environment makes it possible for you to share knowledge and learn new skills, supporting your career and personal growth.' + char(13) + '' + char(13) + 'Our client is currently expanding significantly so this is a great time to be joining the team. You will be given the opportunity to stand out and grow with them. As well as good basic salaries, our clients offers a comprehensive benefits package and a great working environment.' + char(13) + '' + char(13) + 'Skills required:' + char(13) + '' + char(13) + 'C#' + char(13) + '.NET Core' + char(13) + 'ReactJS, TypeScript' + char(13) + 'JavaScript, HTML5, CSS3' + char(13) + 'AWS' + char(13) + 'SQL' + char(13) + 'Azure' + char(13) + 'Great communication skills' + char(13) + 'Strong problem-solving skills' + char(13) + '');
                INSERT INTO Jobs (Title, Location, Department, Salary, Description) VALUES ('Senior Security Software Engineer', 'South East London, London', 'Software', 55000, 'We are looking for a talented Technical Lead to join our growing community of experts and become a key part of one of the biggest and highest - profile digital transformation programmes in the world.' + char(13) + ' ' + char(13) + 'Using fresh ideas and leading edge technologies - and putting the user at the centre of everything we do -we create innovative digital solutions that make a difference to the lives of our 22 million users.' + char(13) + '');
                INSERT INTO Jobs (Title, Location, Department, Salary, Description) VALUES ('Full-Stack Developer', 'Broadwater, Stevenage', 'Software', 40000, 'You will be given the opportunity to work on a challenging mix of short and long term projects that make a positive contribution to society. They deliver wide ranging project including AR/VR, machine learning and web and mobile applications.');
                INSERT INTO Jobs (Title, Location, Department, Salary, Description) VALUES ('Senior Systems Engineer', 'Bowerdean, High Wycombe', 'Defence', 55000, 'We are looking for a contract Senior Systems Engineer to help design next generation sonar systems for applications in warfare. The Senior Systems Engineer will ideally have experience of working across the product lifecycle, working knowledge of using DOORS, and a background of working in markets such as defence, naval, and aerospace.');
                INSERT INTO Jobs (Title, Location, Department, Salary, Description) VALUES ('Teacher training opportunity', 'Guildford', 'Education', 19000, 'Are you an aspiring teacher looking to build your classroom experience whilst gaining your QTS?' + char(13) + '' + char(13) + 'Would you like to work in a supportive environment to kick start your career in education?' + char(13) + '' + char(13) + 'An outstanding Primary school in Guildford are searching for a Graduate Teaching Assistant to join their team as a Trainee Teacher in September 2020. This is a two-year contract working 8.30am-4pm full-time.' + char(13) + '');
                INSERT INTO Jobs (Title, Location, Department, Salary, Description) VALUES ('Teacher', 'West London, London', 'Education', 33000, 'We are a friendly Catholic school looking to appoint an enthusiastic KS2 Year 6 teacher for September 2020. The successful applicant will work as part of a team in a very supportive environment. This post would suit an NQT or an experienced teacher.' + char(13) + '' + char(13) + 'We are a happy and caring school. Pupils and staff work together to provide high quality inclusive education within the framework of the Catholic faith. We view all our children equally and work with each individual to reach his/her full potential. All this is only possible by the distinctive sense of team effort which characterizes our school.' + char(13) + '');
                ");
        }

        public override void Down()
        {
        }
    }
}